### PR TITLE
Handle case-insensitive "connection" header

### PR DESCRIPTION
**Pull request by CharlesOkwuagwu**

### CODE REVIEW

**Comment by CrowdHailer** [comment]
Tests aren't passing

**Comment by CharlesOkwuagwu** [comment]
I've fixed the issue with the pattern match that was failing

**Comment by CrowdHailer** [comment]
Thanks,

Can you add a test. also an entry to the changelog. Just start a new section at the top under master (in place of a release version)

**Comment by CharlesOkwuagwu** [comment]
This is a very minor change to the internal workings ... does it really warrant a change in the build number?

**Comment by CrowdHailer** [comment]
No necessarily but it will be part of the list of changes that makes up the next release.

Also I don't think there is any harm releasing even just this under a patch bump.

**Comment by CharlesOkwuagwu** [comment]
> ...also an entry to the changelog. Just start a new section at the top under master (in place of a release version)

Not sure how to word this `change`/`fix`/ `update `

**Comment by CrowdHailer** [comment]
Fixed

https://keepachangelog.com/en/1.0.0/

**Comment by CrowdHailer** [comment]
Handled by #122

**Pull request closed without merging**
