### PR TITLE
Add path_raw to Request

### PR DESCRIPTION
**Pull request by varnerac**
Adds a path_raw field to the Raxx.Request struct and populates it.

### CODE REVIEW

**Comment by varnerac** [comment]
This is an alternative that I prefer to https://github.com/CrowdHailer/raxx/pull/103

Not sure if you want `path_raw` to have a type of `nil | binary` or if `nil` should convert to `""` if you go with this option.

**Comment by CrowdHailer** [comment]
Can you add an entry to the CHANGELOG

**Comment by CrowdHailer** [comment]
Just put it under `## ongoing`

**Comment by varnerac** [comment]
done

**Comment by CrowdHailer** [comment]
Thanks. I don't even believe this to be a breaking change so I think I can push it as `0.15.1`

**Pull request merged**
